package com.hciproject.exploresite.poi

import androidx.compose.ui.text.LinkAnnotation
import com.hciproject.exploresite.R

data class PointOfInterest(
    
    val name: String,
    val location: LinkAnnotation,
    val image: Int,
    val address: String, //Indirizzo del POI com via/viale/piazza, cap, città e provincia in caso la città non è una provincia, es una cosa a napoli scrivi Napoli una cosa a pozzuoli scrivi Pozzuoli (NA)
    val basePrice: Double, //Prezzo del biglietto base, quello standard che si vedeva affianco al nome del POI nel prototipo
    val detailedPrice: String, //Prezzi dettagliati di tutte le opzioni, in pratica quello che visualizzavi premendo sul prezzo nel prototipo
    val baseOpeningTime: String, //Orario base di apertura, quello che visualizzavi sotto il titolo nel prototipo
    val detailedOpeningTime: String, //Orario dettagliato, quello che visualizzavi quando premevi l'orario base
    val baseJourneyDuration: String, //Orario di percorrenza da mettere nell'ovale
    val detailedJourneyDuration: String, //Orario di percorrenza che leggi quando lo premevi
    val baseAccessibility: POIAccessibility, //Tipologia di accessibilità che vedevi nell'ovale, definiti come boolean, vedi il data class POIAccessibility
    val detailedAccessibility: String, //Quello che vedevi scritto qunado premevi sull'ovale dell'accessibilità
    val ticketShop: LinkAnnotation?, //Link alla biglietteria ufficiale
    val suggestionNumber: Int, //Numero di "Suggerisce" che vedavamo anche nel prototipo, considera un numero inventato però abbastanza plausibile per il luogo che è
    val description: String, //Descrizione, testo della prima delle 3 card
    val descriptionImage: Int, //Immagine della prima delle 3 card, comportati come per l'immagine del POI che ti ho detto prima
    val curiosity1: String,//Titolo della seconda card, tipo "Un po di storia...", "Lo sapevi che..." cose così.
    val curiosity1Title: String,//Contenuto della seconda card
    val curiosity1Image: Int,//Immagine della seconda delle 3 card
    val curiosity2: String,//Contentuo della terza card
    val curiosity2Title: String,//Titolo della terza card
    val curiosity2Image: Int,//Immagine della terza delle 3 card
    val latitude: Double,//Latitudine GPS del punto su maps, la si copia premendo tasto destro sul punto
    val longitude: Double,//Longitudine GPS del punto su maps, la si copia premendo tasto destro sul punto
    val type: POICategory,//Categoria del punto di interesse
)

enum class POICategory{
    CULINARY,
    ARCHEOLOGICAL,
    MUSEUM,
    RELIGIOUS,
    ARCHITECTURE
}

data class POIAccessibility(
    val wheelchair: Boolean,
    val deaf: Boolean,
    val blind: Boolean,
)

val CulturalPOI = listOf(
    PointOfInterest(
        "Reggia di Caserta",
        LinkAnnotation.Url("https://maps.google.com/?q=Reggia+di+Caserta"),
        R.drawable.reggia_di_caserta_primary,
        "Piazza Carlo di Borbone, 81100, Caserta",
        18.00,
        "Il prezzo indicato è il prezzo del biglietto base, senza agevolazioni. Le agevolazioni offerte dalla Reggia di Caserta sono:\n\n- Gratuito per minori di 18 anni\n- Ridotto a 2€ per un’età compresa tra 18 e 24 anni\n\nAl prezzo viene aggiunto 1€ in caso di acquisto online con prevendita",
        "8:30\n19:15",
        "Reggia di Caserta ha i seguenti orari di servizio:\n\nOrario di apertura: 8:30\nOrario di chiusura: 19:15\n\nUltimo ingresso consentito alle 18:15",
        "4:00",
        "Il tempo medio di percorrenza di una visita completa della Reggia di Caserta è di circa 4 ore",
        POIAccessibility(true, true, true),
        "Accessibilitò della Reggia di Caserta:\n\nPer le persone con disabilità motorie:\nParcheggi per disabili\nAscensori dedicati\nServizio navetta dedicato\n\nPer le persone ipoacusiche:\nAudioguide con tecnologia ad induzione magnetica\n\nPer le persone ipovedenti:\nPlastici tattili\nGuide tattili",
        LinkAnnotation.Url("https://www.ticketone.it/artist/reggia-caserta/reggia-di-caserta-1818672/"),
        378491,
        "La Reggia di Caserta è la residenza reale più grande al mondo, fu commissionata da Re Carlo di Borbone nel 1752 e progettata da Luigi Vanvitelli.",
        R.drawable.reggia_di_caserta_description,
        "Un po' di storia...",
        "Re Carlo di Borbone fece costruire la residenza reale nell’entroterra casertano, anziché a Napoli, per fare in modo che fosse al sicuro da qualsiasi bombardamento navale.",
        R.drawable.reggia_di_caserta_curiosity1,
        "Lo sapevi che...",
        "Nell’Episodio I della saga di Star Wars, la Reggia di Caserta è stata trasformata nell'iconico Palazzo Reale del pianeta Naboo.",
        R.drawable.reggia_di_caserta_curiosity2,
        41.07331516989688,
        14.327097240221528,
        POICategory.ARCHITECTURE
    ),
    PointOfInterest(
        "Castel dell'Ovo",
        LinkAnnotation.Url("https://maps.google.com/?q=Castel+dell+Ovo+Napoli"),
        R.drawable.castel_dell_ovo_primary,
        "Via Eldorado, 3, 80132, Napoli",
        0.00,
        "L'ingresso al Castel dell'Ovo è completamente gratuito per tutti i visitatori.",
        "9:00\n18:30",
        "Il Castel dell'Ovo è aperto dal lunedì al sabato dalle 9:00 alle 18:30, mentre nei giorni festivi e la domenica dalle 9:00 alle 14:00. Ultimo ingresso consentito 30 minuti prima della chiusura.",
        "1:30",
        "La visita autonoma del castello, delle sue sale interne e delle terrazze panoramiche richiede circa un'ora e mezza.",
        POIAccessibility(false, true, false),
        "Accessibilità del Castel dell'Ovo:\n\nDisabilità motorie: Accesso limitato a causa di rampe ripide e pavimentazione irregolare in pietra.\n\nDisabilità auditive: Sono disponibili guide testuali all'ingresso del monumento.",
        LinkAnnotation.Url("https://ingressi.comune.napoli.it/"),
        154320,
        "Il Castel dell'Ovo è the castello più antico della città di Napoli e sorge sull'isolotto di Megaride, dove secondo la leggenda sbarcò la sirena Partenope.",
        R.drawable.castel_dell_ovo_description,
        "La leggenda dell'uovo",
        "Il suo nome deriva da una leggenda legata al poeta latino Virgilio, che avrebbe nascosto nelle segrete della fortezza un uovo magico capace di sorreggere l'intero castello e la città.",
        R.drawable.castel_dell_ovo_curiosity1,
        "Vista sul Golfo",
        "Dalla Terrazza dei Cannoni, situata sulla cima del castello, si gode di una delle viste più spettacolari e complete del Golfo di Napoli e del Vesuvio.",
        R.drawable.castel_dell_ovo_curiosity2,
        40.828221,
        14.247511,
        POICategory.ARCHITECTURE
    ),
    PointOfInterest(
        "Arco di Traiano",
        LinkAnnotation.Url("https://maps.google.com/?q=Arco+di+Traiano+Benevento"),
        R.drawable.arco_di_traiano_primary,
        "Via Traiano, 82100, Benevento",
        0.00,
        "Trattandosi di un monumento a cielo aperto situato in una zona pedonale pubblica, l'accesso è interamente gratuito.",
        "0:00\n24:00",
        "Il monumento è liberamente visibile a qualsiasi ora del giorno e della notte. Di sera è suggestivamente illuminato.",
        "0:30",
        "Il tempo consigliato per osservare dettagliatamente tutti i bassorilievi scolpiti sulle facciate dell'arco è di 30 minuti.",
        POIAccessibility(true, true, true),
        "Accessibilità dell'Arco di Traiano:\n\nDisabilità motorie: Perfettamente accessibile in carrozzina trovandosi su un piano stradale livellato e privo di barriere architettoniche.\n\nDisabilità visive: Pannelli didattici con scritte ad alto contrasto posizionati nelle immediate vicinanze.",
        null,
        89432,
        "L'Arco di Traiano di Benevento è un arco trionfale eretto tra il 114 e il 117 d.C. in onore dell'imperatore Traiano, per celebrare l'apertura della via Appia Traiana.",
        R.drawable.arco_di_traiano_description,
        "Unico al mondo",
        "È considerato l'arco trionfale romano meglio conservato al mondo, grazie alla straordinaria integrità dei rilievi che ne ricoprono interamente le pareti.",
        R.drawable.arco_di_traiano_curiosity1,
        "La Porta Aurea",
        "In epoca medievale l'arco perse la sua funzione puramente celebrativa e venne incorporato nella cinta muraria cittadina, prendendo il nome di Porta Aurea.",
        R.drawable.arco_di_traiano_curiosity2,
        41.133056,
        14.779444,
        POICategory.ARCHITECTURE
    ),
    PointOfInterest(
        "Castello di Arechi",
        LinkAnnotation.Url("https://maps.google.com/?q=Castello+di+Arechi+Salerno"),
        R.drawable.castello_di_arechi_primary,
        "Via Francesco Sanseverino, 84121, Salerno",
        6.00,
        "Il prezzo base del biglietto è di 6.00€, presenta le seguenti riduzioni:\n\n- 3.00€ per ragazzi, studenti e scolaresche\n- Gratuito per guide turistiche e persone con disabilità e accompagnatori.",
        "9:00\n17:00",
        "Il Castello di Arechi è aperto dal martedì al sabato dalle 9:00 alle 17:00 e la domenica dalle 9:00 alle 15:30. Il lunedì è chiuso per manutenzione settimanale.",
        "2:00",
        "Il tempo medio per visitare la fortezza, i giardini esterni e il museo medievale interno è di circa 2 ore.",
        POIAccessibility(false, true, true),
        "Il Castello di Arechi non pienamente accessibile a causa della ripida conformazione della collina e delle scale storiche, è stato modernizzato con alcuni ascensori ma non è ancora completamente accessibile in sedia a rotelle. È possibile richiedere guide cartacee dettagliate e il personale di supporto è pronto a comunicare con la LIS.",
        null,
        112450,
        "Il Castello di Arechi è una fortezza medievale situata ad un'altezza di circa 300 metri sul livello del mare, che domina la città e l'intero golfo di Salerno.",
        R.drawable.castello_di_arechi_description,
        "Mai espugnato",
        "Grazie alla sua posizione e alle fortificazioni volute dal duca longobardo Arechi II, la roccaforte divenne il fulcro difensivo del ducato e non fu mai espugnata militarmente.",
        R.drawable.castello_di_arechi_curiosity1,
        "La torre bastarda",
        "Nel settore a caccia del castello sorge una torre d'avvistamento distaccata chiamata 'Torre Bastarda', utilizzata per anticipare gli assalti provenienti dal mare.",
        R.drawable.castello_di_arechi_curiosity2,
        40.686389,
        14.759444,
        POICategory.ARCHITECTURE
    ),
    PointOfInterest(
        "Castello di Gesualdo",
        LinkAnnotation.Url("https://maps.google.com/?q=Castello+di+Gesualdo"),
        R.drawable.castello_di_gesualdo_primary,
        "Piazza Neviera, 83040, Gesualdo (AV)",
        5.00,
        "Il prezzo standard del biglietto d'ingresso è di 5.00€, con le seguenti riduzioni:\n\n- Ridotto a 3€ per ragazzi dai 6 ai 18 anni, studenti universitari e residenti del comune di Gesualdo\n- Gratuito per bambini sotto i 6 anni e persone con disabili e accompagnatore.",
        "10:00\n19:00",
        "Il castello è aperto sabato e domenica dalle 10:00 alle 13:00 e dalle 16:00 alle 19:00. Dal lunedì al venerdì è accessibile solo su prenotazione per gruppi organizzati.",
        "1:30",
        "La durata stimata per il percorso guidato che attraversa la corte, i saloni storici e le cantine è di un'ora e mezza.",
        POIAccessibility(false, true, true),
        "Il Castello è parzialmente accessibile solo al piano terra, in quanto si raggiunge seguendo una strada storica in pietra con pendenze molto ripide, inoltre i piani superiori presentano scale storiche non attrezzate con montascale. Sono ammessi i cani guida.",
        LinkAnnotation.Url("https://www.diyticket.it/artists/1261/castello-di-gesualdo-avellino"),
        43120,
        "Il Castello di Gesualdo fu la dimora del celebre madrigalista Carlo Gesualdo, uno dei più importanti e rivoluzionari compositori del tardo Rinascimento italiano.",
        R.drawable.castello_di_gesualdo_description,
        "Il Principe della Musica",
        "Carlo Gesualdo trasformò la rude fortezza militare medievale in una sfarzosa e raffinata corte rinascimentale, indu ospitò poeti, filosofi e musicisti.",
        R.drawable.castello_di_gesualdo_curiosity1,
        "Fantasmi e note lontane",
        "Leggende locali raccontano che l'anima tormentata del principe, che uccise la prima moglie per gelosia, si aggiri ancora tra le mura del castello suonando il liuto nelle notti di luna piena.",
        R.drawable.castello_di_gesualdo_curiosity2,
        41.005278,
        15.0725,
        POICategory.ARCHITECTURE
    ),
    PointOfInterest(
        "Scavi di Pompei",
        LinkAnnotation.Url("https://maps.google.com/?q=Scavi+di+Pompei"),
        R.drawable.scavi_di_pompei_primary,
        "Via Villa dei Misteri, 2, 80045, Pompei (NA)",
        20.00,
        "Il biglietto di ingresso, chiamato Pompei Express, costa 20.00€ a persona, mentre il biglietto Pompei Plus, che include ai servizi dell'Express anche l'accesso alle ville suburbane, costa 25.00€ a persona. Il biglietto Express viene offerto a 2€ per i cittadini europei di età compresa tra 18 e 24 anni, mentre è gratuito per i minori di 18 anni, per i portatori di handicap e per l'accompagnatore. La prevendita online del biglietto aggiuge 1.00€ al costo.",
        "9:00\n17:00",
        "Gli Scavi di Pompei seguono due tipi di orari:\n\n- Orario estivo dal 1° aprile al 31 ottobre tutti i giorni 9:00 alle 19:30, con ultimo ingresso alle 18:00\n- Orario invernale dal 1º novembre al 31 marzo tutti i giorni dalle 9:00 alle 17:00, con ultimo ingresso alle 15:30",
        "4:00",
        "Data l'enorme estensione del sito archeologico, una visita standard richiede mediamente almeno 4 ore di cammino.",
        POIAccessibility(true, true, true),
        "Il sito offre l'itinerario 'Pompei per tutti', un percorso facilitato privo di barriere architettoniche appositamente studiato per visitatori con mobilità ridotta e passeggini. È possibile richiedere guide cartacee e l'uso di una guida che conosca la LIS.",
        LinkAnnotation.Url("https://pompeii.vivaticket.it/it/tour/pompeii/4661"),
        1254890,
        "Pompei è uno dei siti archeologici più famosi al mondo. L'intera città romana fu sepolta e cristallizzata dall'eruzione del Vesuvio nel 79 d.C.",
        R.drawable.scavi_di_pompei_description,
        "I calchi in gesso",
        "Grazie al metodo ideato dall'archeologo Giuseppe Fiorelli, fu possibile colare del gesso nei vuoti lasciati dai corpi nella cenere, ricreando gli ultimi istanti di vita delle vittime.",
        R.drawable.scavi_di_pompei_curiosity1,
        "I graffiti sui muri",
        "Sulle pareti delle case di Pompei sono ancora visibili scritte elettorali, insulti, dichiarazioni d'amore e persino insegne commerciali con i prezzi del vino.",
        R.drawable.scavi_di_pompei_curiosity2,
        40.748889,
        14.484722,
        POICategory.ARCHEOLOGICAL
    ),
    PointOfInterest(
        "Anfiteatro Campano",
        LinkAnnotation.Url("https://maps.google.com/?q=Anfiteatro+Campano"),
        R.drawable.anfiteatro_campano_primary,
        "Piazza I Ottobre, 81055, Santa Maria Capua Vetere (CE)",
        6.00,
        "Il costo del biglietto intero è di 6.00€ e include l'ingresso al vicino Museo dei Gladiatori, viene ridotto a 2.00€ per i cittadini UE con età tra 18 e 24 anni, mentre è gratuito per i minori di 18 anni, i docenti, le persone con disabilità e accompagnatore.",
        "9:00\n19:00",
        "L'Anfiteatro Campano segue tre orari di apertura diversi per periodo dell'anno:\n\n- Orario invernale, da novembre a febbraio, aperto dal martedì al sabato dalle 9:00 alle 17:00, con ultima visita alle 16:30\n- Orario primaverile e autunnale, da marzo ad aprile e da settembre ad ottobre, dalle 9:00 alle 19:00, con ultima visita alle 18:00.\n- Orario estivo, da maggio ad agosto, dalle 9:00 alle 20:15, con ultimo ingresso alle 19:30.\n\nChiuso tutti i lunedì per riposo settimanale.",
        "1:45",
        "La visita approfondita dell'arena, dei suggestivi sotterranei e del polo museale annesso impegna circa 1 ora e 45 minuti.",
        POIAccessibility(false, true, true),
        "L'area dell'anfiteatro è accessibile alle carrozzine tramite rampe dedicate, mentre i sotterranei sono parzialmente visitabili con l'ausilio del personale a causa di scale ripide e passaggi storici non rettificati.",
        LinkAnnotation.Url("https://portale.museiitaliani.it/b2c/it/buyTicketless/f595b131-5531-4a54-91ac-880d0c054308"),
        145320,
        "L'Anfiteatro Campano era, per dimensioni dell'epoca, il secondo anfiteatro più grande del mondo romano, superato soltanto dal Colosseo di Roma.",
        R.drawable.anfiteatro_campano_description,
        "La rivolta di Spartaco",
        "Proprio in questo luogo e all'interno della sua rinomata scuola gladiatoriale ebbe inizio nel 73 a.C. la celebre rivolta degli schiavi guidata dal gladiatore Spartaco.",
        R.drawable.anfiteatro_campano_curiosity1,
        "Sotterranei intatti",
        "I sotterranei dell'Anfiteatro Campano sono mirabilmente conservati e mostrano ancora i passaggi strutturali usati per sollevare le gabbie delle belve nell'arena.",
        R.drawable.anfiteatro_campano_curiosity2,
        41.086111,
        14.250000,
        POICategory.ARCHEOLOGICAL
    ),
    PointOfInterest(
        "Teatro Romano di Benevento",
        LinkAnnotation.Url("https://maps.google.com/?q=Teatro+Romano+Benevento"),
        R.drawable.teatro_romano_di_benevento_primary,
        "Piazza Ponzio Telesino, 82100, Benevento",
        5.00,
        "Il costo del biglietto è 5.00€, mentre è ridotto a 2€ per i ragazzi dai 18 ai 24 anni residenti in UE. È gratuito per i minorenni, per guide turistiche, docenti e persone con disabilità e accompagnatore.",
        "9:00\n19:30",
        "Aperto tutti i giorni dell'anno tranne a Natale e Capodanno, con orari di apertura dalle 9:00 alle 19:30 e ultimo ingresso alle 19:00.",
        "1:00",
        "La passeggiata archeologica tra le gradinate e i reperti esposti nell'area esterna dura circa un'ora.",
        POIAccessibility(true, true, true),
        "L'accesso al piano dell'orchestra e alla parte bassa della cavea è interamente pavimentato e accessibile a persone con disabilità motorie.",
        LinkAnnotation.Url("https://portale.museiitaliani.it/b2c/it/buyTicketless/70a7bbc8-81d1-46ad-84ff-57be9d616be3"),
        98450,
        "Inaugurato dall'imperatore Adriano nel II secolo d.C., lo splendido Teatro Romano di Benevento poteva ospitare originariamente oltre 10.000 spettatori.",
        R.drawable.teatro_romano_di_benevento_description,
        "Un'acustica leggendaria",
        "La struttura vanta ancora oggi un'acustica impeccabile, motivo per cui viene regolarmente utilizzata in estate per concerti e rappresentazioni teatrali di rilievo.",
        R.drawable.teatro_romano_di_benevento_curiosity1,
        "Sepolto dalle case",
        "Nel corso dei secoli il teatro venne abbandonato e interamente ricoperto da abitazioni private. Fu riscoperto e liberato solo a partire dagli anni '20 del Novecento.",
        R.drawable.teatro_romano_di_benevento_curiosity2,
        41.130278,
        14.771944,
        POICategory.ARCHEOLOGICAL
    ),
    PointOfInterest(
        "Parco Archeologico di Paestum",
        LinkAnnotation.Url("https://maps.google.com/?q=Parco+Archeologico+Paestum"),
        R.drawable.parco_archeologico_di_paestum_primary,
        "Via Magna Graecia, 919, 84047, Capaccio Paestum (SA)",
        15.00,
        "Il costo del biglietto varia in base alla stagione:\n\n- In alta stagione, ovvero da marzo a novembre, il costo è di 15€.\n\n- In bassa stagione il costo è di 6.00€. Il biglietto è ridotto a 2.00€ tutto l'anno per i cittadini UE con età compresa tra i 18 e i 24 anni, mentre è gratuito per i minori e per le persone con disabilità e accompagnatore.",
        "8:30\n19:30",
        "Il parco è aperto tutti i giorni dalle 8:30 alle 19:30, ma resta chiuso i giorni di Natale e Capodanno. La biglietteria chiude alle 18:30 ma l'ultimo ingresso è alle 19:00.",
        "3:00",
        "La visita guidata o autonoma dei tre imponenti templi dorici greci e delle collezioni del museo richiede circa 3 ore.",
        POIAccessibility(true, true, true),
        "Il parco archeologico dispone di percorsi in terra battuta adatti alle sedie a rotelle. Il museo è dotato di rampe e ascensori per l'accesso ad ogni parte visitabile",
        LinkAnnotation.Url("https://parchipaestumvelia.cultura.gov.it/info-biglietti/"),
        542100,
        "Paestum, l'antica Poseidonia greca, è un sito archeologico di fama mondiale noto per i suoi tre maestosi templi dorici straordinariamente conservati.",
        R.drawable.parco_archeologico_di_paestum_description,
        "Il finto Tempio di Nettuno",
        "Nonostante il nome tradizionale attribuito dai primi archeologi, gli studi moderni hanno dimostrato che il tempio più grande era in realtà dedicato alla dea Era.",
        R.drawable.parco_archeologico_di_paestum_curiosity1,
        "La Tomba del Tuffatore",
        "Nel museo di Paestum è custodita la celebre Tomba del Tuffatore, l'unico esempio giunto fino a noi di pittura greca d'età classica a figure umane.",
        R.drawable.parco_archeologico_di_paestum_curiosity2,
        40.421389,
        15.006667,
        POICategory.ARCHEOLOGICAL
    ),
    PointOfInterest(
        "Parco Archeologico di Aeclanum",
        LinkAnnotation.Url("https://maps.google.com/?q=Parco+Archeologico+Aeclanum"),
        R.drawable.parco_archeologico_di_aeclanum_primary,
        "Via Nazionale Appia, 83036, Mirabella Eclano (AV)",
        0.00,
        "L'ingresso all'area archeologica statale di Aeclanum è completamente gratuito.",
        "9:00\n18:00",
        "Aperto dal lunedì al sabato dalle 9:00 alle 18, mentre la domenica e i festivi dalle 9:00 alle 13:00. L'ultimo ingresso garantito è mezz'ora prima della chiusura.",
        "1:15",
        "Il percorso tra i resti monumentali della città romana richiede poco più di un'ora di cammino.",
        POIAccessibility(true, true, false),
        "Il sentiero principale è pianeggiante e percorribile in carrozzina, ma in alcuni punti è possibile trovate brevi tratti dell'antica Via Appia in pietra lavica, che potrebbero rendere difficile la spinta autonoma delle carrozzine.",
        LinkAnnotation.Url("https://cultura.gov.it/evento/apertura-pasquetta-2026/"),
        24500,
        "Aeclanum fu un importante centro commerciale e militare romano della stirpe dei Sanniti Irpini, situato in posizione strategica lungo la storica via Appia.",
        R.drawable.parco_archeologico_di_aeclanum_description,
        "Le terme pubbliche",
        "Tra i resti più spettacolari dell'area spicca il grande impianto termale di epoca imperiale, che conserva ancora porzioni di pavimenti decorati a mosaico.",
        R.drawable.parco_archeologico_di_aeclanum_curiosity1,
        "L'assedio di Silla",
        "Durante la guerra sociale nell'89 a.C., la città si oppose a Roma e fu cinta d'assedio e conquistata dal generale Silla, che la diede parzialmente alle fiamme.",
        R.drawable.parco_archeologico_di_aeclanum_curiosity2,
        41.053056,
        15.004167,
        POICategory.ARCHEOLOGICAL
    ),
    PointOfInterest(
        "Museo Archeologico Nazionale di Napoli (MANN)",
        LinkAnnotation.Url("https://maps.google.com/?q=MANN+Napoli"),
        R.drawable.museo_archeologico_nazionale_di_napoli_primary,
        "Piazza Museo, 19, 80135, Napoli",
        22.00,
        "Il biglietto d'ingresso costa 22.00€ a persona, ma esistono diverse agevolazioni:\n\n- Ridotto a 2€ per i giovani UE dai 18 ai 24 anni.\n- Gratuito per i minori di 18 anni, per persone con disabilità e accompagnatore\n- Gratuito per tutti la prima domenica di ogni mese, il 25 aprile, il 2 giugno e il 4 novembre.\n- Biglietto Family per due adulti 40.00€.",
        "9:00\n19:30",
        "Aperto tutti i giorni dalle 9:00 alle 19:30. Chiuso il martedì, o il mercoledì se il martedì è festivo, per riposo settimanale. Chiuso anche a Natale, Capodanno e il 1º maggio",
        "3:00",
        "Data l'immensa ricchezza delle collezioni storiche (Farnese, Egizia ed Ercolanese), si consiglia una permanenza di almeno 3 ore.",
        POIAccessibility(true, true, true),
        "Il museo è completamente accessibile grazie ad ascensori e rampe interne. Sono disponibili percorsi tattili su prenotazione per visitatori non vedenti.",
        LinkAnnotation.Url("https://tickets.museoarcheologiconapoli.it/catalog/4D055402-7632-B083-0D75-019DAAA891F2"),
        895400,
        "Il MANN è considerato uno dei più importanti e ricchi musei archeologici al mondo, celebre in particolare per i reperti di epoca romana estratti a Pompei ed Ercolano.",
        R.drawable.museo_archeologico_nazionale_di_napoli_description,
        "Il Gabinetto Segreto",
        "Il museo custodisce una famosissima collezione di arte erotica antica proveniente dagli scavi vesuviani, rimasta censurata e sbarrata al pubblico per secoli.",
        R.drawable.museo_archeologico_nazionale_di_napoli_curiosity1,
        "La Collezione Egizia",
        "La sezione egizia del MANN è la terza più importante d'Italia per numero di reperti e una delle più antiche in assoluto d'Europa.",
        R.drawable.museo_archeologico_nazionale_di_napoli_curiosity2,
        40.853333,
        14.250556,
        POICategory.MUSEUM
    ),
    PointOfInterest(
        "Museo Campano di Capua",
        LinkAnnotation.Url("https://maps.google.com/?q=Museo+Campano+Capua"),
        R.drawable.museo_campano_di_capua_primary,
        "Via Museo Campano, 68, 81043, Capua (CE)",
        5.00,
        "Il biglietto d'ingresso base costa 6.00€, con le seguenti riduzioni:\n\n- 4.00€ per studenti universitari, insegnanti e ultra 65enni.\n- 15.00€ per le scolaresche\n\n- Gratuito per i bambini sotto i 14 anni e per le persone con disabilità e accompagnatori.",
        "9:00\n13:30",
        "Il Museo Campano è aperto dal martedì al venerdì dalle 9:00 alle 13:30, mentre il sabato e la domenica dalle 9:00 alle 13:30 e dalle 15:00 alle 18:30.\nLunedì è il giorno di chiusura settimanale.",
        "2:00",
        "La visita approfondita delle trenta sale espositive disposte all'interno del palazzo richiede circa 2 ore.",
        POIAccessibility(true, true, true),
        "Il palazzo d'epoca è stato adeguato con ascensori moderni e rampe per garantire la mobilità in sedia a rotelle in quasi tutte le sale principali.",
        null,
        54120,
        "Ospitato nel rinascimentale Palazzo Antignano, il Museo Campano custodisce la più vasta collezione archeologica della Campania antica dopo quella del MANN.",
        R.drawable.museo_campano_di_capua_description,
        "Le Matres Matutae",
        "La collezione più iconica e unica al mondo è quella delle 'Madri di Capua': centinaia di statue in tufo del VI-II secolo a.C. raffiguranti divinità della fertilità con neonati in braccio.",
        R.drawable.museo_campano_di_capua_curiosity1,
        "I danni della guerra",
        "Nel 1943 il museo fu centrato in pieno da un bombardamento aereo. Fortunatamente gran parte delle preziose sculture si salvò poiché era stata preventivamente nascosta nei sotterranei.",
        R.drawable.museo_campano_di_capua_curiosity2,
        41.108333,
        14.214167,
        POICategory.MUSEUM
    ),
    PointOfInterest(
        "Museo del Sannio",
        LinkAnnotation.Url("https://maps.google.com/?q=Museo+del+Sannio+Benevento"),
        R.drawable.museo_del_sannio_primary,
        "Piazza Matteotti, 82100, Benevento",
        4.00,
        "Il biglietto d'ingresso per il museo e il chiostro costa 4.00€ a persona, ridotto a 2€ per i residenti della provincia di Benevento, per gli studenti universitari, per gli ultra 65enni e per docenti e gruppi di almeno 20 persone.\n- Gratuito per le persone con disabilità e accompagnatori.",
        "9:00\n19:00",
        "Il museo è aperto dal martedì alla domenica dalle 9:00 alle 19:00, con ultimo ingresso alle 18:30, mentre il lunedì è chiuso.",
        "2:00",
        "Il percorso storico, che spazia dall'archeologia sannita all'arte medievale, richiede una visita di circa 2 ore.",
        POIAccessibility(true, true, true),
        "Il museo è pienamente accessibile: Le strutture includono ascensori interni per superare i dislivelli e servizi igienici attrezzati per visitatori con disabilità.",
        LinkAnnotation.Url("hthttps://retemuseale.provincia.benevento.it/pianifica"),
        42150,
        "Il Museo del Sannio è la principale istituzione museale beneventana, ospitata nello splendido e storico complesso monumentale attiguo alla Chiesa di Santa Sofia.",
        R.drawable.museo_del_sannio_description,
        "Il Tempio di Iside",
        "Il museo vanta una straordinaria e ricca sezione egizia composta interamente da reperti provenienti dal Tempio di Iside che sorgeva a Benevento in epoca imperiale.",
        R.drawable.museo_del_sannio_curiosity1,
        "I capitelli parlanti",
        "Incluso nel biglietto vi è il chiostro medievale, famoso per i suoi storici capitelli scolpiti, ognuno dei quali narra scene bibliche o mitologiche diverse.",
        R.drawable.museo_del_sannio_curiosity2,
        41.130000,
        14.781111,
        POICategory.MUSEUM
    ),
    PointOfInterest(
        "Museo Archeologico Provinciale di Salerno",
        LinkAnnotation.Url("https://maps.google.com/?q=Museo+Archeologico+Provinciale+Salerno"),
        R.drawable.museo_archeologico_provinciale_di_salerno_primary,
        "Via San Benedetto, 28, 84122, Salerno",
        0.00,
        "L'ingresso al museo archeologico è completamente gratuito per tutti i visitatori per disposizione promozionale della Provincia di Salerno.",
        "9:00\n19:30",
        "Il museo è aperto dal martedì alla domenica dalle 9:00 alle 19:30, il lunedì è chiuso.",
        "1:30",
        "L'ordinato percorso espositivo cronologico si sviluppa su due piani e richiede circa un'ora e mezza di tempo.",
        POIAccessibility(true, true, true),
        "Struttura dotata di rampe d'accesso esterne, servoscala e ascensore idoneo al trasporto di visitatori in carrozzina, tuttavia l'accesso al primo piano non è dotato di ascensori o montascale.",
        null,
        38400,
        "Situato nell'antico complesso monastico di San Benedetto, il museo illustra in modo dettagliato la storia di Salerno e del suo territorio dalla preistoria al l'età romana.",
        R.drawable.museo_archeologico_provinciale_di_salerno_description,
        "La Testa di Apollo",
        "Il pezzo più celebre del museo è una magnifica testa bronzea di Apollo del I secolo a.C., recuperata nel 1930 impigliata nelle reti di un pescatore nel golfo salernitano.",
        R.drawable.museo_archeologico_provinciale_di_salerno_curiosity1,
        "Gli Etruschi a Salerno",
        "Il museo espone una ricca collezione di vasi e armi provenienti dal vicino sito archeologico di Fratte, a testimonianza dell'antica presenza etrusca nella zona.",
        R.drawable.museo_archeologico_provinciale_di_salerno_curiosity2,
        40.680556,
        14.764444,
        POICategory.MUSEUM
    ),
    PointOfInterest(
        "Museo Irpino",
        LinkAnnotation.Url("https://maps.google.com/?q=Museo+Irpino+Avellino"),
        R.drawable.museo_irpino_primary,
        "Corso Europa, 83100, Avellino",
        0.00,
        "L'accesso alle sale del Museo Irpino, le visite guidate e i laboratori sono totalmente gratuiti.",
        "9:00\n19:00",
        "Il Museo Irpino è aperto dal martedì al sabato dalle 9:00 alle 13:00 e dalle 16:00 alle 19:00, con ultimo ingresso 30 minuti prima della chiusura. La domenica e il lunedì è chiuso.",
        "1:30",
        "La visita completa della sezione archeologica e di quella dedicata alla storia risorgimentale richiede circa 90 minuti.",
        POIAccessibility(true, true, true),
        "La struttura rispetta pienamente le normative vigenti sulle barriere architettoniche, disponendo di ampi ascensori, rampe e bagni per disabili. Inoltre, il museo organizza periodicamente visite guidate e percorsi tattili progettati per persone con disabilità visive.",
        null,
        21300,
        "Il Museo Irpino raccoglie e custodisce le principali testimonianze storiche, preistoriche e archeologiche rinvenute nel territorio della provincia di Avellino.",
        R.drawable.museo_irpino_description,
        "I fieri guerrieri Sanniti",
        "Il museo ospita una notevole collezione di cinturoni, lance e armature in bronzo appartenute ai guerrieri Irpini che combatterono duramente contro Roma.",
        R.drawable.museo_irpino_curiosity1,
        "I moti del 1820",
        "Una sezione intera è dedicata al Risorgimento e ricorda che i primi moti carbonari italiani partirono proprio da Avellino guidati dagli ufficiali Morelli e Silvati.",
        R.drawable.museo_irpino_curiosity2,
        40.913889,
        14.789167,
        POICategory.MUSEUM
    ),
    PointOfInterest(
        "Complesso Monumentale di Santa Chiara",
        LinkAnnotation.Url("https://maps.google.com/?q=Santa+Chiara+Napoli"),
        R.drawable.complesso_monumentale_di_santa_chiara_primary,
        "Via Santa Chiara, 49/c, 80134, Napoli",
        0.00,
        "L'accesso alla Basilica è gratuito, mentre l'ingresso per il Chiostro Maiolicato, il museo e l'area archeologica costa 7.00€ con le seguenti riduzioni:\n\n- 5.00€ per gli studenti universitari sotto i 26 anni, insegnanti, ultra 65enni.\n- 4.00€ per ragazzi e scolaresche.\n- Gratuito per i bambini sotto i 7 anni e per persone con disabilità e accompagnatore.",
        "9:30\n17:30",
        "Il Chiostro e il Museo sono aperti dal lunedì al sabato dalle 9:30 alle 17:30, mentre la domenica e i festivi dalle 10:00 alle 14:30. L'ultimo ingresso è consentito 30 minuti prima dell'orario di chiusura.\n\nLa Basilica è aperta tutti i giorni dalle 7:30 alle 13:00 e dalle 16:30 alle 20:00. Durante le funzioni liturgiche le visite turistiche sono sospese.",
        "1:30",
        "Il tempo ideale per passeggiare lungo i viali del chiostro e ammirare gli affreschi e le maioliche è di circa un'ora e mezza.",
        POIAccessibility(true, true, true),
        "Il chiostro è accessibile in sedia a rotelle grazie a rampe laterali che aggirano i gradini storici. Servizi igienici idonei presenti all'interno.",
        null,
        412500,
        "Fondati nel 1310 da re Roberto d'Angiò, la Basilica e il Monastero di Santa Chiara rappresentano il più grande edificio di culto in stile gotico della città di Napoli.",
        R.drawable.complesso_monumentale_di_santa_chiara_description,
        "Le maioliche campestri",
        "Il celebre chiostro delle Clarisse fu trasformato nel Settecento da D.A. Vaccaro, che rivestì i 64 pilastri ottagonali con splendide 'riggiole' maiolicate dipinte a mano.",
        R.drawable.complesso_monumentale_di_santa_chiara_curiosity1,
        "Il bombardamento del 1943",
        "Durante la Seconda Guerra Mondiale un terribile bombardamento distrusse l'interno barocco accumulatosi nei secoli. La basilica fu ricostruita riportandola alla sobria veste gotica originaria.",
        R.drawable.complesso_monumentale_di_santa_chiara_curiosity2,
        40.846750,
        14.252222,
        POICategory.RELIGIOUS
    ),
    PointOfInterest(
        "Cattedrale di San Michele Arcangelo (Duomo di Casertavecchia)",
        LinkAnnotation.Url("https://maps.google.com/?q=Duomo+Casertavecchia"),
        R.drawable.duomo_di_casertavecchia_primary,
        "Piazza Vescovado, 81100, Casertavecchia (CE)",
        0.00,
        "L'accesso alla Cattedrale di San Michele Arcangelo è totalmente libero e gratuito per tutti i visitatori durante tutto l'anno.",
        "9:00\n18:00",
        "Il Duomo è aperto tutti i giorni, con orario di apertura estivo dalle 9:00 alle 13:00 e dalle 15:30 alle 22:30, mentre l'orario di apertura invernale è dalle 9:00 alle 13:00 e dalle 15:30 alle 18:00. Durante le funzioni religiose le visite turistiche sono sospese",
        "1:00",
        "La visita completa della navata centrale, della splendida torre campanaria e della cripta inferiore richiede circa 1 ora.",
        POIAccessibility(false, true, false),
        "L'ingresso principale alla chiesa è sprovvisto di una rampa, impedendo l'ingresso in sedia a rotelle.",
        LinkAnnotation.Url("https://www.diocesicaserta.it"),
        65400,
        "La Cattedrale di San Michele Arcangelo a Casertavecchia è uno dei più splendidi esempi di architettura arabo-normanna in Campania, edificata nel XII secolo.",
        R.drawable.duomo_di_casertavecchia_description,
        "Il tiburio decorato",
        "La cupola esterna (tiburio) mostra una forte e suggestiva influenza artistica islamica, caratterizzata da archetti intrecciati e tarsie di pietra grigia e gialla.",
        R.drawable.duomo_di_casertavecchia_curiosity1,
        "La leggenda delle fate",
        "Un'antica leggenda locale narra che le pesantissime colonne di marmo della chiesa furono trasportate fin sulla cima del borgo medievale dalle fate del monte Tifata, tenendole in equilibrio sulla testa.",
        R.drawable.duomo_di_casertavecchia_curiosity2,
        41.097500,
        14.367778,
        POICategory.RELIGIOUS
    ),
    PointOfInterest(
        "Chiesa di Santa Sofia",
        LinkAnnotation.Url("https://maps.google.com/?q=Chiesa+Santa+Sofia+Benevento"),
        R.drawable.chiesa_di_santa_sofia_primary,
        "Piazza Santa Sofia, 82100, Benevento",
        0.00,
        "L'accesso alla chiesa, inclusa nel patrimonio mondiale UNESCO, è gratuito.",
        "9:00\n18:30",
        "Aperta dal lunedì al mercoledì dalle 9:00 alle 12:00 e dalle 16:00 alle 18:30, poi dal giovedì alla domenica dalle 9:00 alle 18:30. Le visite turistiche sono sospese durante la celebrazione della Santa Messa.",
        "0:45",
        "Il tempo consigliato per apprezzare la rarissima struttura geometrica interna e gli affreschi longobardi è di 45 minuti.",
        POIAccessibility(true, true, true),
        "La piazza e l'ingresso alla chiesa sono a livello del suolo, senza gradini, e l'interno è agevole per sedie a rotelle.",
        LinkAnnotation.Url("https://www.comune.benevento.it"),
        215400,
        "Fondata dal duca longobardo Arechi II nel 760, la Chiesa di Santa Sofia è una delle più importanti e meglio conservate testimonianze architettoniche longobarde in Europa.",
        R.drawable.chiesa_di_santa_sofia_description,
        "La pianta unica al mondo",
        "La chiesa presenta una pianta eccezionale: esagonale al centro con colonne disposte a cerchio, che muta in una forma stellare con mura perimetrali circolari.",
        R.drawable.chiesa_di_santa_sofia_curiosity1,
        "Patrimonio dell'Umanità",
        "Dal 2011 la chiesa è stata ufficialmente inserita dall'UNESCO nel patrimonio mondiale all'interno del sito seriale 'I Longobardi in Italia: i luoghi del potere'.",
        R.drawable.chiesa_di_santa_sofia_curiosity2,
        41.130139,
        14.781667,
        POICategory.RELIGIOUS
    ),
    PointOfInterest(
        "Cattedrale di San Matteo (Duomo di Salerno)",
        LinkAnnotation.Url("https://maps.google.com/?q=Duomo+di+Salerno"),
        R.drawable.cattedrale_di_san_matteo_primary,
        "Piazza Alfano I, 84121, Salerno",
        0.00,
        "L'ingresso alla Cattedrale, al quadriportico esterno e alla Cripta barocca sotterranea è interamente gratuito, mentre il museo Diocesano di San Matteo ha un costo di ingresso di 5.00€.",
        "8:30\n20:00",
        "Aperto dal lunedì al sabato dalle 8:30 alle 20:00, la domenica e nei giorni festivi l'orario è dalle 8:30 alle 13:00 e dalle 16:00 alle 20:00 a causa delle liturgie.",
        "1:15",
        "La visita complessiva del corpo della chiesa, del cortile romanico e degli splendidi affreschi della cripta richiede circa 1 ora e un quarto.",
        POIAccessibility(true, true, true),
        "L'accesso al quadriportico e alla chiesa superiore avviene tramite rampa laterale, mentre la cripta è provvista di un montascale dedicato gestito dai custodi, inoltre il personale è disposto ad accompagnare persone con disabilità visive e comunicare con LIS per persone con disabilità visive.",
        LinkAnnotation.Url("https://www.cattedraledisalerno.it"),
        310450,
        "Il Duomo di Salerno, fondato dal condottiero normanno Roberto il Guiscardo nel 1081, custodisce nelle sue fondamenta le spoglie mortali dell'Apostolo ed Evangelista San Matteo.",
        R.drawable.cattedrale_di_san_matteo_description,
        "Una Cripta mozzafiato",
        "La cripta che ospita la tomba di San Matteo è un capolavoro assoluto dell'arte barocca, interamente rivestita di marmi policromi e affrescata nel Seicento da famosi pittori.",
        R.drawable.cattedrale_di_san_matteo_curiosity1,
        "I leoni del portale",
        "All'ingresso del portale d'accesso sono scolpiti un leone e una leonessa che allatta il suo piccolo, simboli medievali del potere e della carità della Chiesa.",
        R.drawable.cattedrale_di_san_matteo_curiosity2,
        40.680000,
        14.759167,
        POICategory.RELIGIOUS
    ),
    PointOfInterest(
        "Santuario di Montevergine",
        LinkAnnotation.Url("https://maps.google.com/?q=Santuario+Montevergine"),
        R.drawable.santuario_di_montevergine_primary,
        "Via Santuario, 83013, Mercogliano (AV)",
        0.00,
        "L'ingresso al Complesso del Santuario è gratuito, mentre l'ingresso al museo abbaziale e alla mostra dei presepi costa 3.00€ a persona.",
        "9:00\n18:00",
        "Aperto dal lunedì al venerdi dalle 9:00 alle 17:00, mentre sabato, domenica e festivi è aperto dalle 9:00 alle 18:00.",
        "2:00",
        "Considerando la visita alla Basilica Antica, alla Basilica Nuova e alle ricche sale degli ex-voto, si consigliano almeno 2 ore.",
        POIAccessibility(true, true, true),
        "La struttura è dotata di ascensori moderni che collegano i vari livelli del santuario sulla montagna, con parcheggio per disabili adiacente all'ingresso, inoltre il personale è disposto ad accompagnare persone con disabilità visive e comunicare con LIS per persone con disabilità visive.",
        LinkAnnotation.Url("https://www.santuariodimontevergine.it"),
        485300,
        "Situato a 1270 metri di quota sul massiccio del monte Partenio, il Santuario di Montevergine è uno dei luoghi di pellegrinaggio mariano più famosi d'Italia.",
        R.drawable.santuario_di_montevergine_description,
        "Mamma Schiavona",
        "L'icona sacra della Madonna è affettuosamente chiamata dai fedeli 'Mamma Schiavona' per via del volto scuro, venerata storicamente come la protettrice degli ultimi ed emarginati.",
        R.drawable.santuario_di_montevergine_curiosity1,
        "La Sindone nascosta",
        "Durante la Seconda Guerra Mondiale, la Sacra Sindone di Torino fu segretamente trasferita e nascosta sotto l'altare di Montevergine per sottrarla ai bombardamenti e alle bramosie di Adolf Hitler.",
        R.drawable.santuario_di_montevergine_curiosity2,
        40.936389,
        14.717222,
        POICategory.RELIGIOUS
    ),
    PointOfInterest(
        "Antica Pizzeria Da Michele",
        LinkAnnotation.Url("https://maps.google.com/?q=Antica+Pizzeria+Da+Michele+Napoli"),
        R.drawable.antica_pizzeria_da_michele_primary,
        "Via Cesare Sersale, 1, 80139, Napoli",
        5.50,
        "Il costo medio di una pizza varia da 5.00€ a 6.00€. Non si accettano prenotazioni telefoniche, si segue l'ordine d'arrivo tramite numero distribuito all'ingresso.",
        "11:00\n23:00",
        "Aperto dal lunedì al sabato dalle 11:00 alle 23:00, la domenica è chiuso.",
        "1:00",
        "Il servizio all'interno è molto dinamico e veloce, strutturato appositamente per far fronte al continuo afflusso di clienti.",
        POIAccessibility(true, true, true),
        "Il locale è situato interamente a piano terra, consentendo un accesso privo di scalini per le persone in sedia a rotelle, inoltre il personale è disposto ad accompagnare persone con disabilità visive e comunicare con LIS per persone con disabilità visive.",
        LinkAnnotation.Url("https://www.damichele.net"),
        925400,
        "Fondata nel 1870, l'Antica Pizzeria Da Michele è considerata il tempio sacro della vera pizza napoletana, servendo storicamente solo due varianti: Margherita e Marinara.",
        R.drawable.antica_pizzeria_da_michele_description,
        "Mangia, prega, ama",
        "La pizzeria è diventata un'icona mondiale ancora più celebre dopo essere apparsa nel film hollywoodiano 'Eat Pray Love' con l'attrice Julia Roberts.",
        R.drawable.antica_pizzeria_da_michele_curiosity1,
        "Lievitazione naturale",
        "La famiglia Condurro si tramanda da generazioni il segreto di una lievitazione dell'impasto che supera le 24 ore, garantendo una pizza incredibilmente soffice e digeribile.",
        R.drawable.antica_pizzeria_da_michele_curiosity2,
        40.849722,
        14.263056,
        POICategory.CULINARY
    ),
    PointOfInterest(
        "Pepe in Grani",
        LinkAnnotation.Url("https://maps.google.com/?q=Pepe+in+Grani+Caiazzo"),
        R.drawable.pepe_in_grani_primary,
        "Vico S. Giovanni Battista, 3, 81013, Caiazzo (CE)",
        7.00,
        "Le pizze gourmet a menù variano dai 7.00€ ai 16.00€, mentre il menù degustrazione costa 45.00€ a persona. È caldamente consigliata la prenotazione online sul sito con diverse settimane d'anticipo.",
        "18:30\n0:30",
        "Aperto esclusivamente a cena dal martedì alla domenica dalle 18:30 a 0:30. Chiuso il lunedì.",
        "1:45",
        "L'esperienza enogastronomica completa di un menù degustazione guidato dura mediamente un'ora e tre quarti.",
        POIAccessibility(true, true, true),
        "Il palazzo storico dispone di un ascensore interno per permettere ai clienti con disabilità motorie di raggiungere le sale disposte sui vari livelli, inoltre il personale è disposto ad accompagnare persone con disabilità visive e comunicare con LIS per persone con disabilità visive.",
        LinkAnnotation.Url("https://www.pepeingrani.it"),
        215400,
        "Pepe in Grani, guidata dal pluripremiato maestro Franco Pepe, è stata nominata più volte come la migliore pizzeria del mondo grazie alla ricerca maniacale su impasti e ingredienti locali.",
        R.drawable.pepe_in_grani_description,
        "La Margherita Sbagliata",
        "La pizza più famosa del locale si chiama 'Margherita Sbagliata': la passata di pomodoro riccio di Caiazzo viene aggiunta a freddo in uscita dal forno per preservarne il sapore intatto.",
        R.drawable.pepe_in_grani_curiosity1,
        "Rilancio del territorio",
        "Il clamoroso successo internazionale di questa pizzeria ha trasformato il piccolo borgo di Caiazzo in una meta di turismo gastronomico globale.",
        R.drawable.pepe_in_grani_curiosity2,
        41.176667,
        14.367500,
        POICategory.CULINARY
    ),
    PointOfInterest(
        "Fabbrica Alberti - Liquore Strega",
        LinkAnnotation.Url("https://maps.google.com/?q=Fabbrica+Alberti+Benevento"),
        R.drawable.fabbrica_alberti_liquore_strega_primary,
        "Piazza Vittoria Colonna, 8, 82100, Benevento",
        0.00,
        "L'ingresso allo Store Storico Alberti e allo Spazio Strega è totalmente gratuito. I tour guidati con degustazione all'interno dello stabilimento di produzione sono disponibili su prenotazione a pagamento.",
        "9:00\n20:00",
        "Lo store è aperto dal lunedì al sabato dalle 9:00 alle 20:00, domenica dalle 9:00 alle 13:30.",
        "1:00",
        "La visita guidata delle sale storiche e la degustazione dei torroni e dei liquori dura circa un'ora.",
        POIAccessibility(true, true, true),
        "Gli spazi commerciali dello stabilimento e i percorsi di visita a piano terra sono privi di barriere ed accessibili in carrozzina, il parcheggio dispone di posti auto dedicati alle persone con disabilità e gli accessi sono dotati di rampre di ingresso, inoltre il personale è disposto ad accompagnare persone con disabilità visive e comunicare con LIS per persone con disabilità visive.",
        LinkAnnotation.Url("https://www.strega.it"),
        134500,
        "La Fabbrica Alberti produce dal lontano 1860 il celeberrimo Liquore Strega e i rinomati torroni di Benevento, simboli della tradizione dolciaria del Sannio.",
        R.drawable.fabbrica_alberti_liquore_strega_description,
        "Le 70 erbe segrete",
        "La ricetta del Liquore Strega è rigidamente segreta; prevede l'infusione di circa 70 erbe e spezie mondiali, tra cui lo zafferano che dona il caratteristico colore giallo acceso.",
        R.drawable.fabbrica_alberti_liquore_strega_curiosity1,
        "Il Premio Letterario",
        "Nel 1947 Guido Alberti fondò, insieme agli intellettuali Maria e Goffredo Bellonci, il 'Premio Strega', divenuto oggi il riconoscimento letterario più importante e ambito d'Italia.",
        R.drawable.fabbrica_alberti_liquore_strega_curiosity2,
        41.132778,
        14.769444,
        POICategory.CULINARY
    ),
    PointOfInterest(
        "Borgo Marinaro di Cetara",
        LinkAnnotation.Url("https://maps.google.com/?q=Cetara+Salerno"),
        R.drawable.borgo_marinaro_di_cetara_primary,
        "Via Marina, 84010, Cetara (SA)",
        0.00,
        "La passeggiata nel borgo antico è libera e gratuita. I prezzi dei piatti e delle degustazioni variano a seconda dei ristoranti e dei laboratori ittici locali.",
        "0:00\n24:00",
        "Il borgo è una località pubblica aperta sempre. Le botteghe artigianali aprono solitamente dalle 9:00 alle 20:00.",
        "2:30",
        "Si consiglia una sosta di circa due ore e mezza per esplorare i vicoli marinari e fermarsi a degustare i piatti tipici nei piccoli ristoranti.",
        POIAccessibility(true, true, true),
        "La zona del lungomare e la via principale sono pianeggianti e facilmente accessibili, tuttavia alcuni viali interni presentano gradinate tipiche della costiera, non necessariamente percorribili per visitare il borgo.",
        LinkAnnotation.Url("https://www.comune.cetara.sa.it"),
        185400,
        "Cetara è un pittoresco e autentico borgo di pescatori situato nella Costiera Amalfitana, celebre nel mondo per la produzione della pregiata Colatura di Alici.",
        R.drawable.borgo_marinaro_di_cetara_description,
        "L'eredità del Garum romano",
        "La Colatura di Alici di Cetara è considerata la diretta discendente del 'Garum', la salsa di pesce fermentata liquida di cui i patrizi romani andavano matti.",
        R.drawable.borgo_marinaro_di_cetara_curiosity1,
        "I Terzigni di rovere",
        "Il prezioso liquido ambrato viene estratto facendo maturare le alici pescate sotto sale all'interno di storiche botti di legno di rovere chiamate 'terzigni'.",
        R.drawable.borgo_marinaro_di_cetara_curiosity2,
        40.641944,
        14.700833,
        POICategory.CULINARY
    ),
    PointOfInterest(
        "Cantine Mastroberardino",
        LinkAnnotation.Url("https://maps.google.com/?q=Cantine+Mastroberardino+Atripalda"),
        R.drawable.cantine_mastroberardino_primary,
        "Via Manfredi, 75, 83042, Atripalda (AV)",
        20.00,
        "Le esperienze di degustazione guidata con visita alle cantine storiche sotterranee partono da un prezzo base di 20.00€ a persona, inoltre è possibile scegliere tra le seguenti esperienze:\n\n- Cru Experience 30.00€\n- Monografiche sui Vitigni 40.00€\n-Taurasi Experience 50.00€\n- Red Emotion 50.00€\n- Stilèma Experience 65.00€\n\n Prenotazione obbligatoria online.",
        "10:00\n19:30",
        "Aperto lunedì dalle 16:00 alle 19:00, da martedì a venerdì dalle 10:00 alle 13:00 e dalle 16:00 alle 19:30, il sabato dalle 10:00 alle 13:00. Chiuso la domenica. I tour partono ad orari prestabiliti.",
        "1:30",
        "Il percorso guidato tra i caveau storici, le botti di rovere e la successiva degustazione con sommelier dura circa 1 ora e mezza.",
        POIAccessibility(true, true, true),
        "Le cantine hanno predisposto percorsi d'accesso idonei per superare le scale che conducono alle storiche grotte sotterranee di affinamento, inoltre il personale è disposto ad accompagnare persone con disabilità visive e comunicare con LIS con persone con disabilità visive.",
        LinkAnnotation.Url("https://mastroberardino.com/visite-in-cantina/"),
        74200,
        "Fondata nel 1750, Mastroberardino è la cantina vitivinicola simbolo dell'Irpinia, celebre per aver salvato dall'estinzione vitigni storici come il Taurasi DOCG, il Fiano e il Greco di Tufo.",
        R.drawable.cantine_mastroberardino_description,
        "Il vino degli Scavi di Pompei",
        "L'azienda è stata scelta dal Ministero della Cultura per ripiantare e coltivare gli antichi vigneti all'interno degli Scavi di Pompei, dando vita al celebre vino 'Villa dei Misteri'.",
        R.drawable.cantine_mastroberardino_curiosity1,
        "Le bottiglie dell'Ottocento",
        "Nei caveau blindati sotterranei della famiglia sono gelosamente custodite rarissime bottiglie storiche risalenti alla fine dell'Ottocento, scampate intatte a due guerre mondiali.",
        R.drawable.cantine_mastroberardino_curiosity2,
        40.921111,
        14.825278,
        POICategory.CULINARY
    )
)